name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.repositories.svg
          token: ${{ secrets.POOP_METRIC }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: lowlighter/metrics
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.POOP_METRIC }}
      - uses: lowlighter/metrics@latest
        with:
         filename: metrics.plugin.isocalendar.svg
         token: ${{ secrets.POOP_METRIC }}
         base: ""
         plugin_isocalendar: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          plugin_poopmap_token: ac8c5c95afc8bc04994574dea94c8746
          plugin_poopmap: yes
